#!/usr/bin/env python3
"""
gen-scope-doc.py — Claude Code PostToolUse 훅
agent-scope.json이 수정될 때마다 agent-scope.md를 자동 재생성한다.

동작:
  1. PostToolUse에서 Write|Edit 툴 호출을 감지
  2. 대상 파일이 agent-scope.json인 경우에만 실행
  3. JSON을 파싱해 소유권 테이블 + 경계 파일 테이블 재생성
  4. 정책 섹션(OQ-1, 브리핑 삽입 규칙)은 이 스크립트에 고정 보존

단일 진실 공급원:
  agent-scope.json  → scope-enforcer.py (기계 판독)
                    → agent-scope.md (gen-scope-doc.py로 자동 생성)

agent-scope.md를 직접 수정하지 말 것 — 다음 JSON 수정 시 덮어쓰여진다.
"""

import json
import sys
import os


REPO_ROOT = os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd())
JSON_PATH = os.path.join(REPO_ROOT, ".agent", "rules", "agent-scope.json")
MD_PATH   = os.path.join(REPO_ROOT, ".agent", "rules", "agent-scope.md")

# 역할 표시 순서
ROLE_ORDER = ["FE", "BE", "PERF", "AI", "PM", "TS", "UX", "QA", "OC"]

# 정책 섹션 (OQ-1 결정 등) — JSON에 없는 서술적 내용. 변경 시 이 스크립트를 수정할 것.
_B = "```"
POLICY_SECTIONS = f"""
---

## 위반 처리 방침 (OQ-1 결정)

파일 영역 제약 위반이 감지되면 **경고 출력 후 계속 진행**한다. 작업을 거부하지 않는다.

**이유:** 프롬프트 레벨 제약은 기술적 강제 수단이 없으므로, 경고를 통해 사용자가 판단할 기회를 주는 것이 더 실용적이다.

Sam의 브리핑에 다음 형식으로 경고를 삽입한다:

{_B}
⚠️ 파일 범위 주의: [파일명]은 [다른 역할]의 소유권 범위에 속합니다.
   필요하다면 [다른 에이전트]와 협의 후 수정하세요.
{_B}

---

## 오케스트레이터 브리핑 삽입 규칙

Sam이 에이전트에게 태스크를 위임할 때, 컨텍스트 브리프의 **마지막 항목**으로 아래 블록을 항상 추가한다:

{_B}
- 파일 범위 제약: [해당 역할의 쓰기 허용 경로 목록]
  (이 범위 외 파일은 수정하지 말 것. 불가피하면 오케스트레이터에게 보고)
{_B}

QA·UX처럼 읽기 전용 역할의 경우:

{_B}
- 파일 범위 제약: 읽기 전용. 파일 수정 금지. 결과는 텍스트 출력만.
{_B}
"""


def format_allow_cell(role: str, rules: dict) -> str:
    """역할의 allow 경로 목록을 MD 셀 문자열로 변환."""
    if rules.get("readonly"):
        label = "피드백은 텍스트 출력만" if role == "UX" else "결과는 텍스트 출력만"
        return f"읽기 전용 ({label})"
    patterns = rules.get("allow", [])
    if not patterns:
        return "—"
    return ", ".join(f"`{p}`" for p in patterns)


def build_ownership_table(scope: dict) -> str:
    """파일 소유권 테이블 마크다운을 생성한다."""
    roles = scope.get("roles", {})
    lines = [
        "## 파일 소유권 테이블\n",
        "| 역할 | 에이전트 | 쓰기 허용 경로 | 읽기 |",
        "|------|---------|--------------|------|",
    ]
    for role in ROLE_ORDER:
        rules = roles.get(role)
        if not rules:
            continue
        agent = rules.get("agent", role)
        allow_cell = format_allow_cell(role, rules)
        lines.append(f"| **{role}** | {agent} | {allow_cell} | 전체 |")
    return "\n".join(lines)


def build_boundary_table(scope: dict) -> str:
    """경계 파일 소유권 테이블 마크다운을 생성한다."""
    boundary      = scope.get("boundary", {})
    boundary_meta = scope.get("boundary_meta", {})
    roles         = scope.get("roles", {})

    if not boundary:
        return ""

    lines = [
        "## 경계 파일 소유권 (OQ-2 결정)\n",
        "단일 파일이 FE·BE 경계에 걸치는 경우 아래 기준으로 결정한다.\n",
        "| 파일 패턴 | 소유 역할 | 근거 |",
        "|-----------|---------|------|",
    ]
    for pattern, owner in boundary.items():
        rationale = boundary_meta.get(pattern, "—")
        agent = roles.get(owner, {}).get("agent", owner)
        lines.append(f"| `{pattern}` | **{owner}** {agent} | {rationale} |")

    # package.json 동적 규칙 (boundary dict에 없는 특수 케이스)
    lines.append(
        "| `package.json` (의존성 추가) | 요청자 역할 | "
        "FE 추가면 Avery, BE 추가면 Blake. 빌드 설정이면 Chase |"
    )
    return "\n".join(lines)


def generate_md(scope: dict) -> str:
    """전체 agent-scope.md 내용을 생성한다."""
    header = (
        "<!-- auto-generated by gen-scope-doc.py — agent-scope.json을 수정하면 자동 갱신됩니다. 직접 수정하지 마세요. -->\n"
        "# Agent File Scope Rules\n\n"
        "에이전트가 파일을 수정할 때 적용되는 소유권 규칙.\n"
        "오케스트레이터(Sam)는 브리핑 시 수신 에이전트에게 이 규칙을 기반으로 "
        "**담당 파일 범위**를 명시적으로 전달한다.\n\n"
        "---\n\n"
    )
    ownership_section = build_ownership_table(scope) + "\n\n---\n\n"
    boundary_section  = build_boundary_table(scope)  + "\n"
    return header + ownership_section + boundary_section + POLICY_SECTIONS


def run_generation():
    """JSON을 읽어 MD를 재생성한다. 성공 시 stdout, 실패 시 stderr."""
    try:
        with open(JSON_PATH, encoding="utf-8") as f:
            scope = json.load(f)
    except Exception as e:
        print(f"⚠️  gen-scope-doc: JSON 읽기 실패 — {e}", file=sys.stderr)
        return False

    try:
        md_content = generate_md(scope)
        with open(MD_PATH, "w", encoding="utf-8") as f:
            f.write(md_content)
        print(f"✅ gen-scope-doc: agent-scope.md 재생성 완료")
        return True
    except Exception as e:
        print(f"⚠️  gen-scope-doc: MD 생성 실패 — {e}", file=sys.stderr)
        return False


def main():
    # stdin에서 훅 입력 읽기
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, Exception):
        # stdin 없이 직접 실행 시 (수동 트리거) 바로 생성
        if sys.stdin.isatty():
            run_generation()
        sys.exit(0)

    tool_name = hook_input.get("tool_name", "")
    if tool_name not in ("Write", "Edit"):
        sys.exit(0)

    file_path = hook_input.get("tool_input", {}).get("file_path", "")
    if not file_path.endswith("agent-scope.json"):
        sys.exit(0)

    run_generation()
    sys.exit(0)


if __name__ == "__main__":
    main()
