steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/puppeteer-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/puppeteer-api:latest'
      - '-f'
      - 'apps/puppeteer-api/Dockerfile'
      - 'apps/puppeteer-api'

  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/puppeteer-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/puppeteer-api:latest'

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'puppeteer-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/puppeteer-api:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/puppeteer-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/puppeteer-api:latest'

